# Generated by Django 6.0.4 on 2026-04-30 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=20, unique=True, verbose_name='Código do Convite')),
                ('is_used', models.BooleanField(default=False, verbose_name='Já foi usado?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
            ],
            options={
                'verbose_name': 'Convite de Cadastro',
                'verbose_name_plural': 'Convites de Cadastro',
            },
        ),
    ]
